# This file is used to run the mailu/setup utility

services:
  redis:
    image: redis:alpine
    networks:
      - default
    restart: always

  development:
    image: ghcr.io/mailu/setup:${DEVELOPMENT}
    networks:
      - web
      - default
    env_file: .env
    environment:
      stable_version: ${STABLE}
      this_version: ${DEVELOPMENT}
      VERSIONS: ${STABLE},${DEVELOPMENT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.setup-development.rule=Host(`${ADDRESS}`) && PathPrefix(`/${DEVELOPMENT}`)
      - traefik.http.routers.setup-development.entrypoints=websecure
      - traefik.http.routers.setup-development.tls.certresolver=letsencrypt
      - traefik.http.services.setup-development.loadbalancer.server.port=80
    depends_on:
      - redis
    restart: always

  stable:
    image: ghcr.io/mailu/setup:${STABLE}
    networks:
      - web
      - default
    env_file: .env
    environment:
      stable_version: ${STABLE}
      this_version: ${STABLE}
      VERSIONS: ${STABLE},${DEVELOPMENT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.setup-root.rule=Host(`${ADDRESS}`) && Path(`/`)
      - traefik.http.routers.setup-root.entrypoints=websecure
      - traefik.http.routers.setup-root.tls.certresolver=letsencrypt
      - traefik.http.routers.setup-root.middlewares=setup-stable-redirect
      - traefik.http.routers.setup-root.service=setup-stable
      - 'traefik.http.middlewares.setup-stable-redirect.redirectregex.regex=^https://setup\.mailu\.io/'
      - 'traefik.http.middlewares.setup-stable-redirect.redirectregex.replacement=https://setup.mailu.io/${STABLE}/'
      - traefik.http.routers.setup-stable.rule=Host(`${ADDRESS}`) && PathPrefix(`/${STABLE}`)
      - traefik.http.routers.setup-stable.entrypoints=websecure
      - traefik.http.routers.setup-stable.tls.certresolver=letsencrypt
      - traefik.http.routers.setup-stable.service=setup-stable
      - traefik.http.services.setup-stable.loadbalancer.server.port=80
    depends_on:
      - redis
    restart: always

networks:
  web:
    external: true
  default:
    external: false
