services:
  development:
    image: ghcr.io/mailu/docs:${DEVELOPMENT}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.docs-development.rule=Host(`${ADDRESS}`) && PathPrefix(`/${DEVELOPMENT}/`)
      - traefik.http.routers.docs-development.entrypoints=websecure
      - traefik.http.routers.docs-development.tls.certresolver=letsencrypt
      - traefik.http.routers.docs-development.middlewares=docs-downloads
      - traefik.http.services.docs-development.loadbalancer.server.port=80
      - 'traefik.http.middlewares.docs-downloads.redirectregex.regex=^https://mailu\.io/([^/]+)/_downloads/(docker-compose\.yml|\.env)'
      - 'traefik.http.middlewares.docs-downloads.redirectregex.replacement=https://raw.githubusercontent.com/Mailu/Mailu/$${1}/docs/compose/$${2}'
    restart: always

  stable:
    image: ghcr.io/mailu/docs:${STABLE}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.docs-root.rule=Host(`${ADDRESS}`) && Path(`/`)
      - traefik.http.routers.docs-root.entrypoints=websecure
      - traefik.http.routers.docs-root.tls.certresolver=letsencrypt
      - traefik.http.routers.docs-root.middlewares=docs-stable-redirect
      - traefik.http.routers.docs-root.service=docs-stable
      - 'traefik.http.middlewares.docs-stable-redirect.redirectregex.regex=^https://mailu\.io/'
      - 'traefik.http.middlewares.docs-stable-redirect.redirectregex.replacement=https://mailu.io/${STABLE}/'
      - traefik.http.routers.docs-stable.rule=Host(`${ADDRESS}`) && PathPrefix(`/${STABLE}/`)
      - traefik.http.routers.docs-stable.entrypoints=websecure
      - traefik.http.routers.docs-stable.tls.certresolver=letsencrypt
      - traefik.http.routers.docs-stable.middlewares=docs-downloads
      - traefik.http.routers.docs-stable.service=docs-stable
      - traefik.http.services.docs-stable.loadbalancer.server.port=80
    restart: always

  oldstable:
    image: ghcr.io/mailu/docs:${OLD_STABLE}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.docs-oldstable.rule=Host(`${ADDRESS}`) && PathPrefix(`/${OLD_STABLE}/`)
      - traefik.http.routers.docs-oldstable.entrypoints=websecure
      - traefik.http.routers.docs-oldstable.tls.certresolver=letsencrypt
      - traefik.http.routers.docs-oldstable.middlewares=docs-downloads
      - traefik.http.services.docs-oldstable.loadbalancer.server.port=80
    restart: always

  legacy:
    image: ghcr.io/mailu/docs:${LEGACY}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.docs-legacy.rule=Host(`${ADDRESS}`) && PathPrefix(`/${LEGACY}/`)
      - traefik.http.routers.docs-legacy.entrypoints=websecure
      - traefik.http.routers.docs-legacy.tls.certresolver=letsencrypt
      - traefik.http.routers.docs-legacy.middlewares=docs-downloads
      - traefik.http.services.docs-legacy.loadbalancer.server.port=80
    restart: always

networks:
  web:
    external: true
